name: speeDGA
description: "App de telemetría de alta precisión con velocímetro y odómetro."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Iconos estándar
  cupertino_icons: ^1.0.8

  # Conexión con la base de datos en la nube
  supabase_flutter: ^2.8.1

  # Acceso al GPS del móvil
  geolocator: ^13.0.1

  # Evita que la pantalla se apague mientras conduces
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Si en el futuro añades imágenes o fuentes personalizadas, irán aquí debajo.